### ISSUE TITLE
Add support for Astro v3

### ISSUE THREAD

**Issue by Marocco2** [delucis/astro-embed#54]
I've just forced it with `npm install --force` and it worked just fine, so adding support shouldn't be trivial

**Comment by delucis** [comment]
Thanks for the issue! Should be as simple as updating `peerDependencies` with `^2.0.0 || ^3.0.0-beta` instead of just `^2.0.0`, then running

Would you be interested in making a PR?

You can see the places that need updating here: https://github.com/search?q=repo%3Adelucis%2Fastro-embed+%22astro%22%3A+%22%5E2.0.0%22&type=code

**Comment by jawills** [comment]
Not sure what I am doing wrong but the embed is not working in astro v3.0 (worked in v2.x). I upgraded the packages, but when the URL or <YouTube /> component is included in the mdx file, nothing is rendered.

**Comment by delucis** [comment]
Thanks for reporting @jawills. Would you mind opening a new issue with some more details about how you’re setting things up, which component you’re using etc.? If you can share a link to a reproduction, that would be ideal.

I know the YouTube component is working in 3.0 as it was used in [a blog post on astro.build on Monday](https://astro.build/blog/vercel-official-hosting-partner/), but haven’t had a chance to try it myself.
